###
POST http://localhost:3003/register
Content-Type: application/json

{
  "fullName": "Tavo Tevas",
  "email": "tavo@tevukas.lt",
  "password": "secret123"
}

###
POST http://localhost:3003/login
Content-Type: application/json

{
  "email": "labas@krabas.com",
  "password": "secret123"
}

###
POST http://localhost:3003/accounts
Content-Type: application/json

{
  "group_id": "2",
  "user_id": "1"
}


###
GET http://localhost:3003/users

###
GET http://localhost:3003/accounts/