###
POST http://localhost:3003/register
Content-Type: application/json

{
  "fullName": "Jonas Jonaitis",
  "email": "jonas@ponas.com",
  "password": "secret123"
}

###
POST http://localhost:3003/login
Content-Type: application/json

{
  "email": "rokasra@gmail.com",
  "password": "secret123"
}


###
GET http://localhost:3003/users